// Code generated by kurento-go-generator. DO NOT EDIT.

package elements

type DtlsConnection struct {
	StreamId     string
	ComponentId  string
	ConnectionId string
	State        DtlsConnectionState
}
