// Code generated by kurento-go-generator. DO NOT EDIT.

package elements

// States of a DTLS connection.
type DtlsConnectionState string

// Implement fmt.Stringer interface
func (t DtlsConnectionState) String() string {
	return string(t)
}

const (
	DTLSCONNECTIONSTATE_NEW        DtlsConnectionState = "NEW"
	DTLSCONNECTIONSTATE_CLOSED     DtlsConnectionState = "CLOSED"
	DTLSCONNECTIONSTATE_FAILED     DtlsConnectionState = "FAILED"
	DTLSCONNECTIONSTATE_CONNECTING DtlsConnectionState = "CONNECTING"
	DTLSCONNECTIONSTATE_CONNECTED  DtlsConnectionState = "CONNECTED"
)
