// Code generated by kurento-go-generator. DO NOT EDIT.

package elements

type IceCandidatePair struct {
	StreamId        string
	ComponentId     int
	LocalCandidate  string
	RemoteCandidate string
}
