// Code generated by kurento-go-generator. DO NOT EDIT.

package elements

type IceCandidatePair struct {
	StreamID        string
	StreamId        string
	ComponentID     int
	ComponentId     int
	LocalCandidate  string
	RemoteCandidate string
}
