// Code generated by kurento-go-generator. DO NOT EDIT.

package elements

import "encoding/json"

type IceCandidate struct {
	Candidate     string
	SdpMid        string
	SdpMLineIndex int
}

func (t IceCandidate) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Candidate     string `json:"candidate"`
		SdpMid        string `json:"sdpMid"`
		SdpMLineIndex int    `json:"sdpMLineIndex"`
		Type          string `json:"__type__"`
		Module        string `json:"__module__"`
	}{
		Candidate:     t.Candidate,
		SdpMid:        t.SdpMid,
		SdpMLineIndex: t.SdpMLineIndex,
		Type:          "IceCandidate",
		Module:        "kurento",
	})
}
