// Code generated by kurento-go-generator. DO NOT EDIT.

package core

// Codec used for transmission of audio.
type AudioCodec string

// Implement fmt.Stringer interface
func (t AudioCodec) String() string {
	return string(t)
}

const (
	AUDIOCODEC_OPUS AudioCodec = "OPUS"
	AUDIOCODEC_PCMU AudioCodec = "PCMU"
	AUDIOCODEC_PCMA AudioCodec = "PCMA"
	AUDIOCODEC_RAW  AudioCodec = "RAW"
)
