// Code generated by kurento-go-generator. DO NOT EDIT.

package core

type IFilter interface {
}

// Base interface for all filters.
// <p>
// This is a certain type of `MediaElement`, that processes media
// injected through its sinks, and delivers the outcome through its sources.
// </p>
type Filter struct {
	MediaElement
}

type Filter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (Filter_builder) GetTypeName() string {
	return "Filter"
}
