// Code generated by kurento-go-generator. DO NOT EDIT.

package core

import (
	"context"
	"fmt"

	"github.com/safermobility/kurento-go-next"
)

type IHub interface {
	GetGstreamerDot(details GstreamerDotDetails) (string, error)
}

// A Hub is a routing `MediaObject`.
// It connects several `endpoints <Endpoint>` together
type Hub struct {
	MediaObject
}

type Hub_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (Hub_builder) GetTypeName() string {
	return "Hub"
}

type HubGetGstreamerDotParams struct {
	Details GstreamerDotDetails `json:"Details"`
}

func (HubGetGstreamerDotParams) OperationName() string {
	return "getGstreamerDot"
}

// Returns a string in dot (graphviz) format that represents the gstreamer elements inside the pipeline
// Returns:
// // The dot graph.
func (elem *Hub) GetGstreamerDot(ctx context.Context, params *HubGetGstreamerDotParams) (string, error) {
	request := kurento.BuildInvoke(elem.Id, params)

	// // The dot graph.
	value, err := kurento.CallSimple[string](ctx, elem.GetConnection(), request)
	if err != nil {
		err = fmt.Errorf("rpc error: %w", err)
	}
	return value, err

}
