// Code generated by kurento-go-generator. DO NOT EDIT.

package core

type IPassThrough interface {
}

// This `MediaElement` that just passes media through
type PassThrough struct {
	MediaElement
}

type PassThrough_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MediaPipeline MediaPipeline
}

func (PassThrough_builder) GetTypeName() string {
	return "PassThrough"
}
