// Code generated by kurento-go-generator. DO NOT EDIT.

package core

type RTCCertificateStats struct {
	Fingerprint          string
	FingerprintAlgorithm string
	Base64Certificate    string
	IssuerCertificateId  string
}
