// Code generated by kurento-go-generator. DO NOT EDIT.

package core

type RTCOutboundRTPStreamStats struct {
	PacketsSent   int64
	BytesSent     int64
	TargetBitrate float64
	RoundTripTime float64
}
