// Code generated by kurento-go-generator. DO NOT EDIT.

package core

type ISessionEndpoint interface {
}

// All networked Endpoints that require to manage connection sessions with remote peers implement this interface.
type SessionEndpoint struct {
	Endpoint
}

type SessionEndpoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (SessionEndpoint_builder) GetTypeName() string {
	return "SessionEndpoint"
}
